name: CD

on:
  workflow_dispatch:

jobs:

  release:
    permissions:
      contents: write

    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.3.2

    - name: Set Version
      run: echo "VERSION=$(poetry version -s)" >> $GITHUB_ENV

#    - name: Create tag
#      uses: actions/github-script@v5
#      with:
#        script: |
#          github.rest.git.createRef({
#            owner: context.repo.owner,
#            repo: context.repo.repo,
#            ref: 'refs/tags/V${{ env.VERSION }}',
#            sha: context.sha
#          })

    - name: Build and publish to pypi
      run: |
        poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
        poetry publish --build

    - name: Create GH release
      uses: ncipollo/release-action@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag: ${{ env.VERSION }}
        name: ${{ env.VERSION }}
        artifacts: "dist/*"
