name: PR

on:
  pull_request:
      branches:
        - main

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10', 3.11]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.3.2
    - name: install dependencies
      run: poetry install --with dev --all-extras
    - name: Run pytest
      env:
        PY_VERSION: ${{ matrix.python-version }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
        PINECONE_ENVIRONMENT: ${{ secrets.PINECONE_ENVIRONMENT }}
      run: |
        api_key=$PINECONE_API_KEY
        first_four=${api_key:0:4}
        last_four=${api_key: -4}
        echo "api_key: ${first_four}...${last_four}"
        poetry run pytest -v --html=report.html --cov pinecone_datasets tests/system
    - name: upload pytest report.html
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: dataset-pytest-report-py${{ matrix.python-version }}
        path: report.html
